CREATE TABLE DW_CUSTOMERS(
CUSTOMER_ID_NORM NUMBER,
FULL_NAME_CLEAN VARCHAR(200),
EMAIL_CLEAN VARCHAR(200),
PHONE_CLEAN VARCHAR(50),
REG_DATE_CLEAN DATE,

EMAIL_VALID_FLAG NUMBER(1),
PHONE_VALID_FLAG NUMBER(1),
REG_DATE_VALID_FLAG NUMBER(1),
NAME_VALID_FLAG NUMBER(1),

DQ_SCORE NUMBER
);

CREATE TABLE DW_ORDERS(
ORDER_ID_CLEAN VARCHAR2(100),
CUSTOMER_ID_NORM NUMBER,
ORDER_DATE_CLEAN DATE,
AMOUNT_NUM NUMBER,
CURRENCY_CLEAN VARCHAR(3),
CUSTOMER_VALID_FLAG NUMBER(1),
ORDER_DATE_VALID_FLAG NUMBER(1),
AMOUNT_VALID_FLAG NUMBER(1),
CURRENCY_VALID_FLAG NUMBER(1),
DQ_SCORE NUMBER
);

CREATE TABLE DW_PAYMENTS(
PAYMENT_ID_CLEAN VARCHAR2(10),
ORDER_ID_NORM NUMBER,
PAYMENT_DATE_CLEAN DATE,
AMOUNT_NUM NUMBER,
PAYMENT_METHOD_CLEAN VARCHAR(20),
ORDER_VALID_FLAG NUMBER(1),
DATE_VALID_FLAG NUMBER(1),
AMOUNT_VALID_FLAG NUMBER(1),
PAYMENT_METHOD_CLEAN_FLAG NUMBER(1),
DQ_SCORE NUMBER
);


CREATE OR REPLACE PROCEDURE CLEANSE_CUSTOMERS AS
BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE DW_CUSTOMERS';

INSERT INTO DW_CUSTOMERS(
CUSTOMER_ID_NORM,
FULL_NAME_CLEAN,
EMAIL_CLEAN,
PHONE_CLEAN,
REG_DATE_CLEAN,
EMAIL_VALID_FLAG,
PHONE_VALID_FLAG,
REG_DATE_VALID_FLAG,
NAME_VALID_FLAG,
DQ_SCORE
)



SELECT

CASE
    WHEN LENGTH(TO_CHAR(TO_NUMBER(REGEXP_REPLACE(customer_id,'[^0-9]','') DEFAULT NULL ON CONVERSION ERROR))) = 1
         THEN TO_NUMBER(REGEXP_REPLACE(customer_id,'[^0-9]','') DEFAULT NULL ON CONVERSION ERROR) * 1000
    WHEN LENGTH(TO_CHAR(TO_NUMBER(REGEXP_REPLACE(customer_id,'[^0-9]','') DEFAULT NULL ON CONVERSION ERROR))) = 2
         THEN TO_NUMBER(REGEXP_REPLACE(customer_id,'[^0-9]','') DEFAULT NULL ON CONVERSION ERROR) * 100
    WHEN LENGTH(TO_CHAR(TO_NUMBER(REGEXP_REPLACE(customer_id,'[^0-9]','') DEFAULT NULL ON CONVERSION ERROR))) = 3
         THEN TO_NUMBER(REGEXP_REPLACE(customer_id,'[^0-9]','') DEFAULT NULL ON CONVERSION ERROR) * 10
    WHEN LENGTH(TO_CHAR(TO_NUMBER(REGEXP_REPLACE(customer_id,'[^0-9]','') DEFAULT NULL ON CONVERSION ERROR))) >= 4
         THEN TO_NUMBER(SUBSTR(TO_CHAR(TO_NUMBER(REGEXP_REPLACE(customer_id,'[^0-9]','') DEFAULT NULL ON CONVERSION ERROR)), -4))
END,


TRIM(REGEXP_REPLACE( REPLACE(full_name, '/', ' '), '[^A-Za-z ]', '')),


CASE WHEN REGEXP_LIKE(email,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN email ELSE NULL END,

CASE
    WHEN LENGTH(REGEXP_REPLACE(phone,'[^0-9]','')) BETWEEN 8 AND 15
    THEN REGEXP_REPLACE(phone,'[^0-9]','')
    ELSE NULL
END,

CASE
    WHEN REGEXP_LIKE(reg_date,'^[0-9]{2}/[0-9]{2}/[0-9]{4}$') THEN TO_DATE(reg_date DEFAULT NULL ON CONVERSION ERROR,'MM/DD/YYYY')
    WHEN REGEXP_LIKE(reg_date,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$') THEN TO_DATE(reg_date DEFAULT NULL ON CONVERSION ERROR,'DD-MM-YYYY')
    WHEN REGEXP_LIKE(reg_date,'^[0-9]{2}-[A-Za-z]{3}-[0-9]{4}$') THEN TO_DATE(reg_date DEFAULT NULL ON CONVERSION ERROR,'DD-MON-YYYY')
    WHEN REGEXP_LIKE(reg_date,'^[0-9]{2}-[A-Za-z]{3,9}-[0-9]{4}$') THEN TO_DATE(reg_date DEFAULT NULL ON CONVERSION ERROR, 'DD-MONTH-YYYY','NLS_DATE_LANGUAGE=ENGLISH')
    WHEN REGEXP_LIKE(reg_date,'^[A-Za-z]{3} [0-9]{2}, [0-9]{4}$') THEN TO_DATE(reg_date DEFAULT NULL ON CONVERSION ERROR,'MON DD, YYYY', 'NLS_DATE_LANGUAGE=ENGLISH')
    ELSE NULL
END,

CASE WHEN REGEXP_LIKE(email,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN 1 ELSE 0 END,

CASE WHEN LENGTH(REGEXP_REPLACE(phone,'[^0-9]','')) = 10 THEN 1 ELSE 0 END,

CASE WHEN REGEXP_LIKE(reg_date,'^[0-9]{2}/[0-9]{2}/[0-9]{4}$') OR REGEXP_LIKE(reg_date,'^[0-9]{2}-[0-9]{2}-[0-9]{4}$') OR REGEXP_LIKE(reg_date,'^[0-9]{2}-[A-Za-z]{3}-[0-9]{4}$') THEN 1 ELSE 0 END,

CASE WHEN INSTR(REPLACE(full_name,CHR(160),' '),' ') > 0 THEN 1 ELSE 0 END,

(
 (CASE WHEN REGEXP_LIKE(email,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN 1 ELSE 0 END)*0.30
 +
 (CASE WHEN LENGTH(REGEXP_REPLACE(phone,'[^0-9]','')) = 10 THEN 1 ELSE 0 END)*0.20
 +
 (CASE
     WHEN REGEXP_LIKE(reg_date,'^[0-9]{2}/[0-9]{2}/[0-9]{4}$') AND TO_DATE(reg_date DEFAULT NULL ON CONVERSION ERROR,'MM/DD/YYYY') IS NOT NULL THEN 1
     WHEN REGEXP_LIKE(reg_date,'^[0-9]{2}-[0-9]{2}-[0-9]{4}$') AND TO_DATE(reg_date DEFAULT NULL ON CONVERSION ERROR,'DD-MM-YYYY') IS NOT NULL THEN 1
     WHEN REGEXP_LIKE(reg_date,'^[0-9]{2}-[A-Za-z]{3}-[0-9]{4}$') AND TO_DATE(reg_date DEFAULT NULL ON CONVERSION ERROR,'DD-MON-YYYY') IS NOT NULL THEN 1
     ELSE 0 END)*0.20
 +
 (CASE WHEN INSTR(REPLACE(full_name,CHR(160),' '),' ') > 0 THEN 1 ELSE 0 END)*0.30
)*100

FROM ST_CUSTOMERS;

COMMIT;
END;
/



CREATE OR REPLACE PROCEDURE CLEANSE_ORDERS AS
BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE DW_ORDERS';

INSERT INTO DW_ORDERS(
ORDER_ID_CLEAN,
CUSTOMER_ID_NORM,
ORDER_DATE_CLEAN,
AMOUNT_NUM,
CURRENCY_CLEAN,
CUSTOMER_VALID_FLAG,
ORDER_DATE_VALID_FLAG,
AMOUNT_VALID_FLAG,
CURRENCY_VALID_FLAG,
DQ_SCORE
)
SELECT

CASE
    WHEN LENGTH(REGEXP_REPLACE(x.order_id,'[^0-9]','')) = 1
        THEN REGEXP_REPLACE(x.order_id,'[^0-9]','') || '000'
    WHEN LENGTH(REGEXP_REPLACE(x.order_id,'[^0-9]','')) = 2
        THEN REGEXP_REPLACE(x.order_id,'[^0-9]','') || '00'
    WHEN LENGTH(REGEXP_REPLACE(x.order_id,'[^0-9]','')) = 3
        THEN REGEXP_REPLACE(x.order_id,'[^0-9]','') || '0'
    WHEN LENGTH(REGEXP_REPLACE(x.order_id,'[^0-9]','')) >= 4
        THEN SUBSTR(REGEXP_REPLACE(x.order_id,'[^0-9]',''),-4)
END AS ORDER_ID_CLEAN,

CASE
    WHEN LENGTH(REGEXP_REPLACE(x.customer_id,'[^0-9]','')) = 1
        THEN REGEXP_REPLACE(x.customer_id,'[^0-9]','') || '000'
    WHEN LENGTH(REGEXP_REPLACE(x.customer_id,'[^0-9]','')) = 2
        THEN REGEXP_REPLACE(x.customer_id,'[^0-9]','') || '00'
    WHEN LENGTH(REGEXP_REPLACE(x.customer_id,'[^0-9]','')) = 3
        THEN REGEXP_REPLACE(x.customer_id,'[^0-9]','') || '0'
    WHEN LENGTH(REGEXP_REPLACE(x.customer_id,'[^0-9]','')) >= 4
        THEN SUBSTR(REGEXP_REPLACE(x.customer_id,'[^0-9]',''),-4)
END AS CUSTOMER_ID_NORM,

CASE
    WHEN REGEXP_LIKE(x.order_date,'^[0-9]{2}/[0-9]{2}/[0-9]{4}$')
         THEN TO_DATE(x.order_date DEFAULT NULL ON CONVERSION ERROR,'MM/DD/YYYY')
    WHEN REGEXP_LIKE(x.order_date,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
         THEN TO_DATE(x.order_date DEFAULT NULL ON CONVERSION ERROR,'YYYY-MM-DD')
    WHEN REGEXP_LIKE(x.order_date,'^[0-9]{2}-[A-Za-z]{3}-[0-9]{4}$')
         THEN TO_DATE(x.order_date DEFAULT NULL ON CONVERSION ERROR,'DD-MON-YYYY','NLS_DATE_LANGUAGE=ENGLISH')
    WHEN REGEXP_LIKE(x.order_date,'^[0-9]{2} [A-Za-z]{3,9} [0-9]{4}$')
         THEN TO_DATE(x.order_date DEFAULT NULL ON CONVERSION ERROR,'DD Month YYYY','NLS_DATE_LANGUAGE=ENGLISH')
    ELSE NULL
END AS ORDER_DATE_CLEAN,

CASE
    WHEN TO_NUMBER(REGEXP_REPLACE(x.amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR) IS NULL THEN NULL
    WHEN TO_NUMBER(REGEXP_REPLACE(x.amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR) < 0
         AND (REGEXP_LIKE(x.amount,'REFUND','i') OR UPPER(x.currency)='REFUND')
        THEN ABS(TO_NUMBER(REGEXP_REPLACE(x.amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR))
    WHEN TO_NUMBER(REGEXP_REPLACE(x.amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR) < 0
         AND NOT REGEXP_LIKE(x.amount,'REFUND','i')
         AND UPPER(x.currency) <> 'REFUND'
        THEN NULL
    ELSE TO_NUMBER(REGEXP_REPLACE(x.amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR)
END AS AMOUNT_NUM,

CASE
    WHEN REGEXP_LIKE(x.amount,'EURO','i') OR REGEXP_LIKE(x.amount,'\bEUR\b','i') THEN 'EUR'
    WHEN REGEXP_LIKE(x.amount,'US[D$]','i') THEN 'USD'
    WHEN REGEXP_LIKE(x.amount,'HUF','i') THEN 'HUF'
    WHEN UPPER(x.currency) IN ('EUR','EURO') THEN 'EUR'
    WHEN UPPER(x.currency) IN ('USD','US$') THEN 'USD'
    WHEN UPPER(x.currency)='HUF' THEN 'HUF'
    WHEN UPPER(x.currency)='REFUND' THEN 'REFUND'
    ELSE NULL
END AS CURRENCY_CLEAN,

CASE WHEN REGEXP_REPLACE(x.customer_id,'[^0-9]','') IS NOT NULL THEN 1 ELSE 0 END AS CUSTOMER_VALID_FLAG,

CASE
    WHEN REGEXP_LIKE(x.order_date,'^[0-9]{2}/[0-9]{2}/[0-9]{4}$')
      OR REGEXP_LIKE(x.order_date,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
      OR REGEXP_LIKE(x.order_date,'^[0-9]{2}-[A-Za-z]{3}-[0-9]{4}$')
      OR REGEXP_LIKE(x.order_date,'^[0-9]{2} [A-Za-z]{3,9} [0-9]{4}$')
        THEN 1 ELSE 0
END AS ORDER_DATE_VALID_FLAG,

CASE
    WHEN
        CASE
            WHEN TO_NUMBER(REGEXP_REPLACE(x.amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR) IS NULL THEN NULL
            WHEN TO_NUMBER(REGEXP_REPLACE(x.amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR) < 0
                 AND NOT REGEXP_LIKE(x.amount,'REFUND','i')
                 AND UPPER(x.currency) <> 'REFUND'
                THEN NULL
            ELSE TO_NUMBER(REGEXP_REPLACE(x.amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR)
        END
    IS NULL THEN 0 ELSE 1 END AS AMOUNT_VALID_FLAG,

CASE
    WHEN
        CASE
            WHEN REGEXP_LIKE(x.amount,'EURO','i') OR REGEXP_LIKE(x.amount,'\bEUR\b','i') THEN 'EUR'
            WHEN REGEXP_LIKE(x.amount,'US[D$]','i') THEN 'USD'
            WHEN REGEXP_LIKE(x.amount,'HUF','i') THEN 'HUF'
            WHEN UPPER(x.currency) IN ('EUR','EURO') THEN 'EUR'
            WHEN UPPER(x.currency) IN ('USD','US$') THEN 'USD'
            WHEN UPPER(x.currency)='HUF' THEN 'HUF'
            WHEN UPPER(x.currency)='REFUND' THEN 'REFUND'
            ELSE NULL
        END
    IS NULL THEN 0 ELSE 1 END AS CURRENCY_VALID_FLAG,

(
    (CASE WHEN REGEXP_REPLACE(x.customer_id,'[^0-9]','') IS NOT NULL THEN 1 ELSE 0 END)*0.25 +
    (CASE
        WHEN REGEXP_LIKE(x.order_date,'^[0-9]{2}/[0-9]{2}/[0-9]{4}$')
          OR REGEXP_LIKE(x.order_date,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
          OR REGEXP_LIKE(x.order_date,'^[0-9]{2}-[A-Za-z]{3}-[0-9]{4}$')
          OR REGEXP_LIKE(x.order_date,'^[0-9]{2} [A-Za-z]{3,9} [0-9]{4}$')
        THEN 1 ELSE 0 END)*0.25 +
    (CASE
        WHEN
            CASE
                WHEN TO_NUMBER(REGEXP_REPLACE(x.amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR) IS NULL THEN NULL
                WHEN TO_NUMBER(REGEXP_REPLACE(x.amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR) < 0
                     AND NOT REGEXP_LIKE(x.amount,'REFUND','i')
                     AND UPPER(x.currency) <> 'REFUND'
                    THEN NULL
                ELSE TO_NUMBER(REGEXP_REPLACE(x.amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR)
            END
        IS NULL THEN 0 ELSE 1 END)*0.25 +
    (CASE
        WHEN
            CASE
                WHEN REGEXP_LIKE(x.amount,'EURO','i') OR REGEXP_LIKE(x.amount,'\bEUR\b','i') THEN 'EUR'
                WHEN REGEXP_LIKE(x.amount,'US[D$]','i') THEN 'USD'
                WHEN REGEXP_LIKE(x.amount,'HUF','i') THEN 'HUF'
                WHEN UPPER(x.currency) IN ('EUR','EURO') THEN 'EUR'
                WHEN UPPER(x.currency) IN ('USD','US$') THEN 'USD'
                WHEN UPPER(x.currency)='HUF' THEN 'HUF'
                WHEN UPPER(x.currency)='REFUND' THEN 'REFUND'
                ELSE NULL
            END
        IS NULL THEN 0 ELSE 1 END)*0.25
) * 100 AS DQ_SCORE

FROM
(
    SELECT st_orders.*, ROW_NUMBER() OVER (PARTITION BY TRIM(order_id) ORDER BY order_date) AS rn
    FROM ST_ORDERS
) x
WHERE rn = 1;

COMMIT;
END;
/




SELECT * FROM dw_orders; 


SELECT COUNT(*) FROM DW_ORDERS WHERE CUSTOMER_ID_NORM IS NULL;
SELECT COUNT(*) FROM ST_ORDERS WHERE CUSTOMER_ID IS NULL;

SELECT COUNT( * ) FROM ST_PAYMENTS WHERE ORDER_ID IS null;


CREATE OR REPLACE PROCEDURE CLEANSE_PAYMENTS AS
BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE DW_PAYMENTS';

INSERT INTO DW_PAYMENTS(
PAYMENT_ID_CLEAN,
ORDER_ID_NORM,
PAYMENT_DATE_CLEAN,
AMOUNT_NUM,
PAYMENT_METHOD_CLEAN,
ORDER_VALID_FLAG,
DATE_VALID_FLAG,
AMOUNT_VALID_FLAG,
PAYMENT_METHOD_CLEAN_FLAG,
DQ_SCORE
)

SELECT

CASE
WHEN LENGTH(REGEXP_REPLACE(payment_id,'[^0-9]',''))=1 THEN LPAD(REGEXP_REPLACE(payment_id,'[^0-9]',''),4,'0')
WHEN LENGTH(REGEXP_REPLACE(payment_id,'[^0-9]',''))=2 THEN LPAD(REGEXP_REPLACE(payment_id,'[^0-9]',''),4,'0')
WHEN LENGTH(REGEXP_REPLACE(payment_id,'[^0-9]',''))=3 THEN LPAD(REGEXP_REPLACE(payment_id,'[^0-9]',''),4,'0')
WHEN LENGTH(REGEXP_REPLACE(payment_id,'[^0-9]',''))>=4 THEN SUBSTR(REGEXP_REPLACE(payment_id,'[^0-9]',''),-4)
END,

CASE
WHEN LENGTH(REGEXP_REPLACE(order_id,'[^0-9]',''))=1 THEN TO_NUMBER(LPAD(REGEXP_REPLACE(order_id,'[^0-9]',''),4,'0'))
WHEN LENGTH(REGEXP_REPLACE(order_id,'[^0-9]',''))=2 THEN TO_NUMBER(LPAD(REGEXP_REPLACE(order_id,'[^0-9]',''),4,'0'))
WHEN LENGTH(REGEXP_REPLACE(order_id,'[^0-9]',''))=3 THEN TO_NUMBER(LPAD(REGEXP_REPLACE(order_id,'[^0-9]',''),4,'0'))
WHEN LENGTH(REGEXP_REPLACE(order_id,'[^0-9]',''))>=4 THEN TO_NUMBER(SUBSTR(REGEXP_REPLACE(order_id,'[^0-9]',''),-4))
ELSE NULL END,

CASE
WHEN REGEXP_LIKE(payment_date,'^[0-9]{2}/[0-9]{2}/[0-9]{4}$')
THEN TO_DATE(payment_date DEFAULT NULL ON CONVERSION ERROR,'MM/DD/YYYY')
WHEN REGEXP_LIKE(payment_date,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
THEN TO_DATE(payment_date DEFAULT NULL ON CONVERSION ERROR,'YYYY-MM-DD')
WHEN REGEXP_LIKE(payment_date,'^[0-9]{2}-[A-Za-z]{3}-[0-9]{4}$')
THEN TO_DATE(payment_date DEFAULT NULL ON CONVERSION ERROR,'DD-MON-YYYY','NLS_DATE_LANGUAGE=ENGLISH')
WHEN REGEXP_LIKE(payment_date,'^[0-9]{2} [A-Za-z]{3,9} [0-9]{4}$')
THEN TO_DATE(payment_date DEFAULT NULL ON CONVERSION ERROR,'DD Month YYYY','NLS_DATE_LANGUAGE=ENGLISH')
ELSE NULL END,

TO_NUMBER(REGEXP_REPLACE(amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR),

CASE
WHEN REGEXP_LIKE(method,'^(BACK_TRANSFER|BANK[_-]?TF|BANK_TRANSFER)$','i')
THEN 'BANK_TRANSFER'
WHEN REGEXP_LIKE(method,'^(PAY[-_]?PAL)$','i')
THEN 'PAYPAL'
WHEN REGEXP_LIKE(method,'^CASH$','i')
THEN 'CASH'
WHEN REGEXP_LIKE(method,'^CARD$','i')
THEN 'CARD'
ELSE NULL END,

CASE WHEN REGEXP_REPLACE(order_id,'[^0-9]','') IS NULL THEN 0 ELSE 1 END,

CASE
WHEN REGEXP_LIKE(payment_date,'^[0-9]{2}/[0-9]{2}/[0-9]{4}$')
OR REGEXP_LIKE(payment_date,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
OR REGEXP_LIKE(payment_date,'^[0-9]{2}-[A-Za-z]{3}-[0-9]{4}$')
OR REGEXP_LIKE(payment_date,'^[0-9]{2} [A-Za-z]{3,9} [0-9]{4}$')
THEN 1 ELSE 0 END,

CASE
WHEN TO_NUMBER(REGEXP_REPLACE(amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR) IS NULL
THEN 0 ELSE 1 END,

CASE
WHEN REGEXP_LIKE(method,'^(BACK_TRANSFER|BANK[_-]?TF|BANK_TRANSFER)$','i')
OR REGEXP_LIKE(method,'^(PAY[-_]?PAL)$','i')
OR REGEXP_LIKE(method,'^CASH$','i')
OR REGEXP_LIKE(method,'^CARD$','i')
THEN 1 ELSE 0 END,

(
(CASE WHEN REGEXP_REPLACE(order_id,'[^0-9]','') IS NULL THEN 0 ELSE 1 END)*0.25 +
(CASE WHEN
 REGEXP_LIKE(payment_date,'^[0-9]{2}/[0-9]{2}/[0-9]{4}$')
 OR REGEXP_LIKE(payment_date,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
 OR REGEXP_LIKE(payment_date,'^[0-9]{2}-[A-Za-z]{3}-[0-9]{4}$')
 OR REGEXP_LIKE(payment_date,'^[0-9]{2} [A-Za-z]{3,9} [0-9]{4}$')
 THEN 1 ELSE 0 END)*0.25 +
(CASE
 WHEN TO_NUMBER(REGEXP_REPLACE(amount,'[^0-9.\-]','') DEFAULT NULL ON CONVERSION ERROR) IS NULL THEN 0 ELSE 1 END)*0.25 +
(CASE
 WHEN REGEXP_LIKE(method,'^(BACK_TRANSFER|BANK[_-]?TF|BANK_TRANSFER)$','i')
  OR REGEXP_LIKE(method,'^(PAY[-_]?PAL)$','i')
  OR REGEXP_LIKE(method,'^CASH$','i')
  OR REGEXP_LIKE(method,'^CARD$','i')
 THEN 1 ELSE 0 END)*0.25
)*100

FROM ST_PAYMENTS;

COMMIT;
END;
/


begin
cleanse_customers;
cleanse_orders;
cleanse_payments;
end;
/

select * from dw_customers;
select * from dw_orders;
select * from dw_payments;






